const OK_CODE = 200;
const BAD_REQUEST_CODE = 400;
const UNAUTHORIZED_CODE = 401;
const FORBIDDEN_CODE = 403;
const SERVER_FAILURE_CODE = 500;
const CREATED_CODE = 201;

export {
  OK_CODE,
  CREATED_CODE,
  BAD_REQUEST_CODE,
  UNAUTHORIZED_CODE,
  FORBIDDEN_CODE,
  SERVER_FAILURE_CODE
};
